<a href="https://colab.research.google.com/github/Pranav-Bavadiya/NLP_Learning/blob/main/NLP_Based_Predictive_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "True.csv"

# Load the latest version
df_true = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "clmentbisaillon/fake-and-real-news-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

df_true['result'] = 0

/tmp/ipython-input-2088360585.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_true = kagglehub.load_dataset(


100%|██████████| 18.1M/18.1M [00:00<00:00, 63.8MB/s]

Extracting zip of True.csv...


In [3]:
file_path = "Fake.csv"
df_false = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "clmentbisaillon/fake-and-real-news-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

df_false['result'] = 1

/tmp/ipython-input-3284246183.py:2: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_false = kagglehub.load_dataset(


Using Colab cache for faster access to the 'fake-and-real-news-dataset' dataset.


In [4]:
df = pd.concat([df_false,df_true],ignore_index=True)

In [5]:
df.sample(5)

title  \
25646  Opposed from the start, the rocky history of N...   
446     Trump Stops Praising Coast Guard’s Harvey Eff...   
7160    So Much For Outreach: Black Staffers Are Jump...   
2719    Newly Leaked Executive Order Will Turn A FRIG...   
9214   JUST RELEASED: Texts Between Anti-Trump Muelle...   

                                                    text       subject  \
25646  (Reuters) - Negotiators from Canada, Mexico an...  politicsNews   
446    Donald Trump has now become well known for his...          News   
7160   When Republicans examined why they lost the 20...          News   
2719   It seems the Trump administration will stop at...          News   
9214   Fox News just revealed what we knew but it s o...      politics   

                    date  result  
25646   August 16, 2017        0  
446    September 2, 2017       1  
7160       April 1, 2016       1  
2719    February 2, 2017       1  
9214        Dec 12, 2017       1

In [6]:
df.drop(columns=['date'],inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44898 entries, 0 to 44897
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   title    44898 non-null  object
 1   text     44898 non-null  object
 2   subject  44898 non-null  object
 3   result   44898 non-null  int64 
dtypes: int64(1), object(3)
memory usage: 1.4+ MB


In [8]:
df.sample(5)

title  \
14782  NEW ACCUSATION AGAINST BERNIE SANDERS Exposes ...   
21359  LEFTIST Resentment Peddler, Larry David (Net W...   
19820  LEAKED EMAIL: Hillary’s Team Caught Bashing “B...   
9000    Teen Records Himself Abusing Girl: ‘This Is W...   
7837    Greedy Oil CEO Fires 20 Percent Of Employees,...   

                                                    text    subject  result  
14782  By now, it s pretty clear that Bernie doesn t ...   politics       1  
21359  And why wouldn t he? The leftist comedy writer...  left-news       1  
19820  As a Catholic, I m not sure what offends me mo...  left-news       1  
9000   A young man recorded himself as he maliciously...       News       1  
7837   The World s largest oil field service, Schlumb...       News       1

In [9]:
df['subject'].value_counts()

subject
politicsNews       11272
worldnews          10145
News                9050
politics            6841
left-news           4459
Government News     1570
US_News              783
Middle-east          778
Name: count, dtype: int64

In [32]:
df['result'].value_counts()

result
1    23481
0    21417
Name: count, dtype: int64

In [10]:
df = pd.get_dummies(df,columns=['subject'],drop_first=True)

you should do one hot after train test split but here for speed we are doing before it

In [11]:
df.sample(5)

title  \
43653  Rape cases fuel anti-migrant angst in Italy ah...   
30305  Democrats plot uphill fight against some Trump...   
6088    Secret Trump University Papers Reveal How Bus...   
32865  Illinois House Democrats advance FY 2017 budge...   
6232    Former Israeli Prime Minister BLASTS Israeli ...   

                                                    text  result  \
43653  ROME (Reuters) - Rape allegations leveled agai...       0   
30305  WASHINGTON (Reuters) - U.S. Senate Democrats p...       0   
6088   It is now clear why Donald Trump attacked the ...       1   
32865  SPRINGFIELD, Ill (Reuters) - Illinois took ano...       0   
6232   It appears that the curtain that hides the tru...       1   

       subject_Middle-east  subject_News  subject_US_News  subject_left-news  \
43653                False         False            False              False   
30305                False         False            False              False   
6088                 False          True            False              False   
32865                False         False            False              False   
6232                 False          True            False              False   

       subject_politics  subject_politicsNews  subject_worldnews  
43653             False                 False               True  
30305             False                  True              False  
6088              False                 False              False  
32865             False                  True              False  
6232              False                 False              False

In [12]:
X = df.drop(columns=['result'])
y = df['result']

Train–test split should be performed before fitting any NLP model (BoW, TF-IDF, Word2Vec) to avoid data leakage.  
A single shared text model(bow,tf-idf,word2vec) should be used across all text columns to maintain a common vocabulary or embedding space.  
After vectorization, features from different text columns are provided as separate input feature blocks to the final ML model.

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [15]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 58.2 MB/s eta 0:00:00


In [16]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
from gensim.utils import simple_preprocess

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


simple process auto-matically do word tockenizing,lower and special latter removing

In [17]:
lem = WordNetLemmatizer()
stopwords = set(stopwords.words('english'))

1️⃣ Bag of Words (BoW) / TF-IDF

Input to model:

A list of documents

Each document is a row of raw text (string)

Example:

[
  "good phone",
  "battery life is good"
]


Preprocessing:

Tokenization → handled internally by the vectorizer

Stop-word removal → Yes (commonly used)

Lemmatization → Optional

Stemming → Optional

Best practice:

Pass raw text to CountVectorizer / TfidfVectorizer

Avoid manual tokenization unless required

2️⃣ Word2Vec

Input to model:

A list of tokenized sentences

Each sentence is a list of words

Example:

[
  ["good", "phone"],
  ["battery", "life", "good"]
]


Preprocessing:

Tokenization → Mandatory

Stop-word removal → Recommended

Lemmatization → Recommended

Stemming → Optional

Best practice:

Preprocess text before training Word2Vec

Preserve sentence boundaries

3️⃣ Deep Learning Models (LSTM, BERT, etc.)

Input to model:

Raw text (string)

Preprocessing:

Tokenization → handled by model tokenizer

Stop-word removal → Not recommended

Lemmatization → Not recommended

In [22]:
corups_raw = []
for col in ['text','title']:
  sen = []
  for sent in X_train[col]:
    words = simple_preprocess(sent)
    word_list = [word for word in words if word not in stopwords]
    sen.append(' '.join(word_list))
  corups_raw.append(sen)

you can do stop word in direct bow and tf-idf  
CountVectorizer(stop_words="english")  
TfidfVectorizer(stop_words="english")

Lemmatization is optional for BoW and TF-IDF, but it is not handled internally and must be done manually if required.

In [23]:
corups_raw[0][0]

'athens reuters turkish president tayyip erdogan said thursday president donald trump unfortunate decision recognize jerusalem capital israel trampling international laws erdogan speaking athens talks prime minister alexis tsipras also said turkey wanted see lasting solution island cyprus said greek cypriots avoiding talks'

In [97]:
corups_raw[1][0]

'turkey erdogan says jerusalem decision tramples law'

In [24]:
len(corups_raw)

2

In [18]:
corups_tock = []
for col in ['text','title']:
  for sent in X_train[col]:
    sen = simple_preprocess(sent)
    word_list = [lem.lemmatize(word) for word in sen if word not in stopwords]
    corups_tock.append(word_list)

In [26]:
len(corups_tock)

71836

In [27]:
corups_tock[0]

['athens',
 'reuters',
 'turkish',
 'president',
 'tayyip',
 'erdogan',
 'said',
 'thursday',
 'president',
 'donald',
 'trump',
 'unfortunate',
 'decision',
 'recognize',
 'jerusalem',
 'capital',
 'israel',
 'trampling',
 'international',
 'law',
 'erdogan',
 'speaking',
 'athens',
 'talk',
 'prime',
 'minister',
 'alexis',
 'tsipras',
 'also',
 'said',
 'turkey',
 'wanted',
 'see',
 'lasting',
 'solution',
 'island',
 'cyprus',
 'said',
 'greek',
 'cypriot',
 'avoiding',
 'talk']

📌 Internal Working Summary: BoW, TF-IDF & Word2Vec
🔹 Bag of Words (BoW)

BoW first builds a common vocabulary from all training documents.
Each document is then represented as a fixed-length vector where each value is the count of a word from the vocabulary in that document.

🔹 TF-IDF

TF-IDF also builds a common vocabulary like BoW.
Each document is converted into a vector, but words are weighted based on how frequent they are in the document (TF) and how rare they are across all documents (IDF).

🔹 Word2Vec

Word2Vec builds one global vocabulary and processes text sentence by sentence.
Each word is internally represented as a one-hot vector, and a sliding context window is applied within each sentence to train a neural network that learns dense word embeddings.

Example Text
Doc1: "good phone"
Doc2: "battery life good"

🔹 Bag of Words (BoW)

Vocabulary (from all documents):

['battery', 'good', 'life', 'phone']


Vectors:

Doc1 → [0, 1, 0, 1]
Doc2 → [1, 1, 1, 0]


➡ Each value = word count in the document

🔹 TF-IDF

Same vocabulary:

['battery', 'good', 'life', 'phone']


Vectors (weighted):

Doc1 → [0.0, 0.3, 0.0, 0.7]
Doc2 → [0.6, 0.2, 0.6, 0.0]


➡ Common words (like good) get lower weight, rare words get higher weight

One hot is different  + it is used inside word2vec
voca = ['battery', 'good', 'life', 'phone']  
now it will make vector like this  
battery = [1,0,0,0]  
good = [0,1,0,0]  
life = [0,0,1,0]  
phone = [0,0,0,1]
now sentence will be vectorized for each word's vector using this

## BoW

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer(binary=True,ngram_range=(1,1),max_features=2500)

In [29]:
bow.fit(corups_raw[0]+corups_raw[1])

CountVectorizer(binary=True, max_features=2500)

In [30]:
text_bow_train = bow.transform(corups_raw[0])
title_bow_train = bow.transform(corups_raw[1])

In [31]:
text_bow_train.shape

(35918, 2500)

In [32]:
text_bow_train[0]

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 24 stored elements and shape (1, 2500)>

In [33]:
text_bow_train[0].data

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

it means 377 are 1's and each row has 3959425 columns

In [34]:
text_bow_train[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [35]:
text_bow_train = text_bow_train.toarray()
title_bow_train = title_bow_train.toarray()

In [36]:
X_train_bow = np.concatenate((text_bow_train,title_bow_train),axis=1)
X_train_bow = np.concatenate((X_train_bow,X_train.drop(columns=['text','title']).to_numpy()),axis=1)

In [19]:
corups_raw_test=[]
for col in ['text','title']:
  sen=[]
  for sent in X_test[col]:
    words = simple_preprocess(sent)
    word_list = [word for word in words if word not in stopwords]
    sen.append(' '.join(word_list))
  corups_raw_test.append(sen)

In [53]:
text_bow_test = bow.transform(corups_raw_test[0])
title_bow_test = bow.transform(corups_raw_test[1])

In [54]:
X_test_bow = np.concatenate((text_bow_test.toarray(),title_bow_test.toarray()),axis=1)
X_test_bow = np.concatenate((X_test_bow,X_test.drop(columns=['text','title']).to_numpy()),axis=1)

In [26]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
model_bow = MultinomialNB(alpha=1.0)

In [56]:
model_bow.fit(X_train_bow,y_train)

MultinomialNB()

In [58]:
y_bow_pred = model_bow.predict(X_test_bow)
print(accuracy_score(y_test,y_bow_pred))

0.9795100222717149


## Tf-IDF

In [61]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf = TfidfVectorizer(ngram_range=(1,1),max_features=2500)

In [62]:
tf_idf.fit(corups_raw[0]+corups_raw[1])

TfidfVectorizer(max_features=2500)

In [63]:
text_emtf_train = tf_idf.transform(corups_raw[0]).toarray()
title_emtf_train = tf_idf.transform(corups_raw[1]).toarray()

In [64]:
text_emtf_train[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [65]:
X_train_emtf = np.concatenate((text_emtf_train,title_emtf_train),axis=1)
X_train_emtf = np.concatenate((X_train_emtf,X_train.drop(columns=['text','title']).to_numpy()),axis=1)

In [66]:
text_emtf_test = tf_idf.transform(corups_raw_test[0]).toarray()
title_emtf_test = tf_idf.transform(corups_raw_test[1]).toarray()

In [67]:
X_test_emtf = np.concatenate((text_emtf_test,title_emtf_test),axis=1)
X_test_emtf = np.concatenate((X_test_emtf,X_test.drop(columns=['text','title']).to_numpy()),axis=1)

In [68]:
model_tf = MultinomialNB(alpha=1.0)
model_tf.fit(X_train_emtf,y_train)
y_tf_pred = model_tf.predict(X_test_emtf)
print(accuracy_score(y_test,y_tf_pred))

0.9953229398663697


## Pretrained google-news-300

In [70]:
import gensim

In [38]:
import gensim.downloader as api
w2v_pre = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


ommon Word2Vec functions include most_similar, similarity, doesnt_match, get_vector, and vocabulary checks using key_to_index.

In [39]:
w2v_pre.most_similar('flower')

[('floral', 0.7493643164634705),
 ('flowers', 0.7488503456115723),
 ('roses', 0.697738766670227),
 ('orchid', 0.6928980350494385),
 ('tulip', 0.6629416346549988),
 ('peony', 0.6613222360610962),
 ('blooms', 0.6554170846939087),
 ('blossoms', 0.6527379155158997),
 ('chrysanthemum', 0.6500308513641357),
 ('anthurium', 0.6497662663459778)]

In [40]:
w2v_pre.similarity('man','woman')

np.float32(0.76640123)

In [41]:
w2v_pre.doesnt_match(['love','pain','peace','hate'])

'pain'

In [42]:
'cure' in w2v_pre.key_to_index

True

checks cure exist in dictionary or not

In [43]:
w2v_pre.most_similar(positive=['king','woman'],negative=['man'])

[('queen', 0.7118193507194519),
 ('monarch', 0.6189674139022827),
 ('princess', 0.5902431011199951),
 ('crown_prince', 0.5499460697174072),
 ('prince', 0.5377321839332581),
 ('kings', 0.5236844420433044),
 ('Queen_Consort', 0.5235945582389832),
 ('queens', 0.518113374710083),
 ('sultan', 0.5098593235015869),
 ('monarchy', 0.5087411403656006)]

it means      +king+woman-man

In [44]:
w2v_pre['king']

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

##Word2vec

In [20]:
from gensim.models import Word2Vec

w2v = Word2Vec(
    sentences=corups_tock,
    vector_size=300,
    window=5,
    min_count=2,
    sg=0,          # CBOW
    workers=4,
    epochs=10
)

sg=0 default - cbow , 1 for skip grams  
works = no. of cpu threads

all previous function can be used in this also just word need to exist in vocabulary

In [72]:
w2v.wv.index_to_key

['trump',
 'said',
 'state',
 'president',
 'would',
 'people',
 'year',
 'republican',
 'one',
 'new',
 'clinton',
 'obama',
 'also',
 'government',
 'house',
 'say',
 'reuters',
 'time',
 'donald',
 'american',
 'election',
 'country',
 'right',
 'white',
 'could',
 'party',
 'like',
 'united',
 'campaign',
 'told',
 'two',
 'official',
 'news',
 'last',
 'first',
 'group',
 'law',
 'hillary',
 'washington',
 'day',
 'video',
 'make',
 'former',
 'u',
 'even',
 'get',
 'court',
 'week',
 'vote',
 'medium',
 'security',
 'many',
 'want',
 'national',
 'democrat',
 'may',
 'woman',
 'leader',
 'bill',
 'police',
 'made',
 'russia',
 'political',
 'million',
 'image',
 'back',
 'twitter',
 'know',
 'take',
 'since',
 'way',
 'administration',
 'tax',
 'america',
 'support',
 'think',
 'month',
 'going',
 'percent',
 'according',
 'presidential',
 'senate',
 'member',
 'statement',
 'north',
 'attack',
 'democratic',
 'policy',
 'called',
 'via',
 'report',
 'office',
 'go',
 'well',
 'r

In [73]:
w2v.corpus_count

71836

In [74]:
w2v.wv.similar_by_word('dangerous')

[('reckless', 0.4880845844745636),
 ('irresponsible', 0.4792763590812683),
 ('frightening', 0.46994245052337646),
 ('destructive', 0.4609331786632538),
 ('irrational', 0.45176026225090027),
 ('unpredictable', 0.44446465373039246),
 ('immoral', 0.4174173176288605),
 ('provocative', 0.41575315594673157),
 ('impulsive', 0.4143034815788269),
 ('heartless', 0.4110747277736664)]

In [75]:
w2v.wv['dangerous']

array([-1.7961698 ,  0.04735208,  0.05413593, -1.3320116 , -0.3247088 ,
       -0.5124969 ,  0.3206729 , -0.67239934, -2.264457  , -0.6932508 ,
       -0.45522672,  0.06459332,  0.9590238 ,  0.09591112, -0.10055018,
       -1.2089387 ,  0.47818694,  1.2870584 ,  0.0407572 , -0.8812936 ,
        0.6053595 ,  0.26179576,  0.05508962, -0.85144603, -0.44340694,
        1.0056475 ,  0.5037083 , -1.2238845 , -1.608592  , -0.7066695 ,
        1.9354767 ,  0.02070981,  1.2493464 , -0.84990495,  1.3538672 ,
        1.366378  ,  1.1863717 , -1.8034825 , -0.6726444 , -0.04900995,
       -0.20665205,  0.17767033, -1.4509577 ,  0.69859976, -0.13706517,
       -0.3110075 ,  0.5514981 , -0.48272613, -0.3063118 , -1.4836818 ,
       -1.2650483 , -0.7329154 , -2.2232413 ,  0.19364648, -0.04308381,
       -0.14709869, -0.49609503,  1.4666518 , -0.22825423, -0.7895213 ,
        1.3230509 ,  0.21795206,  0.99712455, -0.47189772, -2.3688378 ,
       -0.09114897, -0.9986755 , -2.3441546 ,  0.89124244, -0.38

In [76]:
w2v.wv['dangerous'].shape

(300,)

##AvgWord2Vec

In [21]:
def avg_word2vec(sent,model,lemmatizer,stopwords_set):
    words = simple_preprocess(sent)
    # Apply stopword removal and lemmatization consistently with corups_tock creation
    filtered_words = [word for word in words if word not in stopwords_set]
    processed_words = [lemmatizer.lemmatize(word) for word in filtered_words]

    vectors = [model[word] for word in processed_words if word in model.key_to_index]

    if len(vectors) == 0:
        return np.zeros(model.vector_size)

    return np.mean(vectors, axis=0)

In [22]:
X_train_w2v = np.concatenate((np.array([avg_word2vec(sent,w2v.wv,lem,stopwords) for sent in X_train['text']]),np.array([avg_word2vec(sent,w2v.wv,lem,stopwords) for sent in X_train['title']])),axis=1)
X_train_w2v = np.concatenate((X_train_w2v,X_train.drop(columns=['text','title']).to_numpy()),axis=1)

In [23]:
X_test_w2v = np.concatenate((np.array([avg_word2vec(sent,w2v.wv,lem,stopwords) for sent in X_test['text']]),np.array([avg_word2vec(sent,w2v.wv,lem,stopwords) for sent in X_test['title']])),axis=1)
X_test_w2v = np.concatenate((X_test_w2v,X_test.drop(columns=['text','title']).to_numpy()),axis=1)

🔹 Multinomial Naive Bayes (MultinomialNB)

📌 Used mainly for text classification

🧠 Works with non-negative, count-based features

✅ Best with Bag of Words and TF-IDF

📂 Common tasks:

Spam detection

Sentiment analysis

Topic classification

⚡ Very fast and memory-efficient

❌ Not suitable for Word2Vec or other continuous embeddings, because it gives negative value feature

In [24]:
from sklearn.linear_model import LogisticRegression

In [27]:
model_w2v = LogisticRegression(max_iter=1000)
model_w2v.fit(X_train_w2v,y_train)
y_w2v_pred = model_w2v.predict(X_test_w2v)
print(accuracy_score(y_w2v_pred,y_test))

0.9997772828507795


In [29]:
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(y_w2v_pred,y_test)

array([[4247,    2],
       [   0, 4731]])

In [31]:
print(classification_report(y_w2v_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4249
           1       1.00      1.00      1.00      4731

    accuracy                           1.00      8980
   macro avg       1.00      1.00      1.00      8980
weighted avg       1.00      1.00      1.00      8980



In [98]:
s1_text = "Donald Trump has been publicly accused of having affairs with several women, most notably adult film star Stormy Daniels and former Playboy model Karen McDougal."
s1_title = "Donald Trump Affair Allegations"
s1_test = np.concatenate((np.array([avg_word2vec(s1_text,w2v.wv,lem,stopwords)]),np.array([avg_word2vec(s1_title,w2v.wv,lem,stopwords)])),axis=1)
s1_test = np.concatenate((s1_test,np.array([0,0,1,0,0,0,0]).reshape(1,7)),axis=1)

In [99]:
print(model_w2v.predict(s1_test))

[1]
