<a href="https://colab.research.google.com/github/Pranav-Bavadiya/NLP_Learning/blob/main/NLP_Based_Predictive_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "True.csv"

# Load the latest version
df_true = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "clmentbisaillon/fake-and-real-news-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

df_true['result'] = 0

/tmp/ipython-input-2088360585.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_true = kagglehub.load_dataset(


100%|██████████| 18.1M/18.1M [00:01<00:00, 11.1MB/s]

Extracting zip of True.csv...


In [3]:
file_path = "Fake.csv"
df_false = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "clmentbisaillon/fake-and-real-news-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

df_false['result'] = 1

/tmp/ipython-input-3284246183.py:2: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df_false = kagglehub.load_dataset(


Using Colab cache for faster access to the 'fake-and-real-news-dataset' dataset.


In [4]:
df = pd.concat([df_false,df_true],ignore_index=True)

In [5]:
df.sample(5)

title  \
12645  DON’T BELIEVE THE POLLS: Massive Silent Majori...   
33228  Pentagon chief would back lifting restrictions...   
22721  Digisexual Robot Pimps, Swamp Chess, Hollywood...   
10516  AMERICANS ARE LAUGHING At Michael Moore When T...   
18881  PROFESSOR Gives Instruction For What’s Accepta...   

                                                    text       subject  \
12645  So many acts of violence and vandalism have be...      politics   
33228  WASHINGTON (Reuters) - U.S. Defense Secretary ...  politicsNews   
22721  Tune in to the Alternate Current Radio Network...   Middle-east   
10516  The Washington Post published a propaganda org...      politics   
18881  FEMALE MUSLIM PROFESSOR SAYS RAPE IS AN ACCEPT...     left-news   

                    date  result  
12645       Oct 23, 2016       1  
33228    April 28, 2016        0  
22721  November 30, 2017       1  
10516       Jun 29, 2017       1  
18881        Apr 1, 2017       1

In [6]:
df.drop(columns=['date'],inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44898 entries, 0 to 44897
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   title    44898 non-null  object
 1   text     44898 non-null  object
 2   subject  44898 non-null  object
 3   result   44898 non-null  int64 
dtypes: int64(1), object(3)
memory usage: 1.4+ MB


In [8]:
df.sample(5)

title  \
1359    Watch Trump Shove Foreign Leader Out Of The W...   
14109  COLLEGE CAMPUS BANS Chalk, Fears Students Migh...   
8373    Sarah Palin Oddly Brings Up Justin Bieber Dur...   
26085  Donald Trump Jr. adds Washington lawyer to leg...   
30884  Russia's Putin congratulates Trump on election...   

                                                    text       subject  result  
1359   Donald Trump met with the other members of NAT...          News       1  
14109  Remember when college campuses were considered...      politics       1  
8373   Sarah Palin is back at it again. Only this tim...          News       1  
26085  WASHINGTON (Reuters) - The president’s oldest ...  politicsNews       0  
30884  MOSCOW (Reuters) - Russian President Vladimir ...  politicsNews       0

In [9]:
df['subject'].value_counts()

subject
politicsNews       11272
worldnews          10145
News                9050
politics            6841
left-news           4459
Government News     1570
US_News              783
Middle-east          778
Name: count, dtype: int64

In [10]:
df = pd.get_dummies(df,columns=['subject'],drop_first=True)

you should do one hot after train test split but here for speed we are doing before it

In [11]:
df.sample(5)

title  \
44411  Trump, UK's May agree that China must do more ...   
24069  Cuban businesswomen seek Rubio meeting as U.S....   
4846    WATCH: Trump Supporter Calls For Sending Blac...   
32493  U.S. Senate advances compromise gun control me...   
16064  HYSTERICAL! President Trump Calls Out Obama: “...   

                                                    text  result  \
44411  LONDON (Reuters) - U.S. President Donald Trump...       0   
24069  HAVANA (Reuters) - An association of Cuban bus...       0   
4846   Donald Trump s pathetic outreach effort to swa...       1   
32493  WASHINGTON (Reuters) - The U.S. Senate on Thur...       0   
16064  President Trump has the line of the day:  The ...       1   

       subject_Middle-east  subject_News  subject_US_News  subject_left-news  \
44411                False         False            False              False   
24069                False         False            False              False   
4846                 False          True            False              False   
32493                False         False            False              False   
16064                False         False            False              False   

       subject_politics  subject_politicsNews  subject_worldnews  
44411             False                 False               True  
24069             False                  True              False  
4846              False                 False              False  
32493             False                  True              False  
16064             False                 False              False

In [12]:
X = df.drop(columns=['result'])
y = df['result']

Train–test split should be performed before fitting any NLP model (BoW, TF-IDF, Word2Vec) to avoid data leakage.  
A single shared text model(bow,tf-idf,word2vec) should be used across all text columns to maintain a common vocabulary or embedding space.  
After vectorization, features from different text columns are provided as separate input feature blocks to the final ML model.

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [15]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 63.1 MB/s eta 0:00:00


In [16]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
from gensim.utils import simple_preprocess

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


simple process auto-matically do word tockenizing,lower and special latter removing

In [17]:
lem = WordNetLemmatizer()
stopwords = set(stopwords.words('english'))

1️⃣ Bag of Words (BoW) / TF-IDF

Input to model:

A list of documents

Each document is a row of raw text (string)

Example:

[
  "good phone",
  "battery life is good"
]


Preprocessing:

Tokenization → handled internally by the vectorizer

Stop-word removal → Yes (commonly used)

Lemmatization → Optional

Stemming → Optional

Best practice:

Pass raw text to CountVectorizer / TfidfVectorizer

Avoid manual tokenization unless required

2️⃣ Word2Vec

Input to model:

A list of tokenized sentences

Each sentence is a list of words

Example:

[
  ["good", "phone"],
  ["battery", "life", "good"]
]


Preprocessing:

Tokenization → Mandatory

Stop-word removal → Recommended

Lemmatization → Recommended

Stemming → Optional

Best practice:

Preprocess text before training Word2Vec

Preserve sentence boundaries

3️⃣ Deep Learning Models (LSTM, BERT, etc.)

Input to model:

Raw text (string)

Preprocessing:

Tokenization → handled by model tokenizer

Stop-word removal → Not recommended

Lemmatization → Not recommended

In [18]:
corups_raw = []
for col in ['text','title']:
  for sent in X_train[col]:
    words = simple_preprocess(sent)
    word_list = [word for word in words if word not in stopwords]
    sen = ' '.join(word_list)
    corups_raw.append(sen)

you can do stop word in direct bow and tf-idf  
CountVectorizer(stop_words="english")  
TfidfVectorizer(stop_words="english")

Lemmatization is optional for BoW and TF-IDF, but it is not handled internally and must be done manually if required.

In [19]:
corups_raw[0]

'athens reuters turkish president tayyip erdogan said thursday president donald trump unfortunate decision recognize jerusalem capital israel trampling international laws erdogan speaking athens talks prime minister alexis tsipras also said turkey wanted see lasting solution island cyprus said greek cypriots avoiding talks'

In [20]:
len(corups_raw)

71836

In [21]:
corups_tock = []
for col in ['text','title']:
  for sent in X_train[col]:
    sen = simple_preprocess(sent)
    word_list = [lem.lemmatize(word) for word in sen if word not in stopwords]
    corups_tock.append(word_list)

In [22]:
len(corups_tock)

71836

In [23]:
corups_tock[0]

['athens',
 'reuters',
 'turkish',
 'president',
 'tayyip',
 'erdogan',
 'said',
 'thursday',
 'president',
 'donald',
 'trump',
 'unfortunate',
 'decision',
 'recognize',
 'jerusalem',
 'capital',
 'israel',
 'trampling',
 'international',
 'law',
 'erdogan',
 'speaking',
 'athens',
 'talk',
 'prime',
 'minister',
 'alexis',
 'tsipras',
 'also',
 'said',
 'turkey',
 'wanted',
 'see',
 'lasting',
 'solution',
 'island',
 'cyprus',
 'said',
 'greek',
 'cypriot',
 'avoiding',
 'talk']

📌 Internal Working Summary: BoW, TF-IDF & Word2Vec
🔹 Bag of Words (BoW)

BoW first builds a common vocabulary from all training documents.
Each document is then represented as a fixed-length vector where each value is the count of a word from the vocabulary in that document.

🔹 TF-IDF

TF-IDF also builds a common vocabulary like BoW.
Each document is converted into a vector, but words are weighted based on how frequent they are in the document (TF) and how rare they are across all documents (IDF).

🔹 Word2Vec

Word2Vec builds one global vocabulary and processes text sentence by sentence.
Each word is internally represented as a one-hot vector, and a sliding context window is applied within each sentence to train a neural network that learns dense word embeddings.

Example Text
Doc1: "good phone"
Doc2: "battery life good"

🔹 Bag of Words (BoW)

Vocabulary (from all documents):

['battery', 'good', 'life', 'phone']


Vectors:

Doc1 → [0, 1, 0, 1]
Doc2 → [1, 1, 1, 0]


➡ Each value = word count in the document

🔹 TF-IDF

Same vocabulary:

['battery', 'good', 'life', 'phone']


Vectors (weighted):

Doc1 → [0.0, 0.3, 0.0, 0.7]
Doc2 → [0.6, 0.2, 0.6, 0.0]


➡ Common words (like good) get lower weight, rare words get higher weight

One hot is different  + it is used inside word2vec
voca = ['battery', 'good', 'life', 'phone']  
now it will make vector like this  
battery = [1,0,0,0]  
good = [0,1,0,0]  
life = [0,0,1,0]  
phone = [0,0,0,1]
now sentence will be vectorized for each word's vector using this

## BoW

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer(binary=True,ngram_range=(1,1),max_features=2500)

In [25]:
sent_em_train = bow.fit_transform(corups_raw)

In [26]:
sent_em_train.shape

(71836, 2500)

In [27]:
sent_em_train[0]

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 24 stored elements and shape (1, 2500)>

In [28]:
sent_em_train[0].data

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

it means 377 are 1's and each row has 3959425 columns

In [29]:
sent_em_train[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [30]:
sent_em_train = sent_em_train.toarray()

In [31]:
corups_raw_test=[]
for col in ['text','title']:
  sen=[]
  for sent in X_test[col]:
    words = simple_preprocess(sent)
    word_list = [word for word in words if word not in stopwords]
    sen.append(' '.join(word_list))
  corups_raw_test.append(sen)

In [56]:
X_train_new = X_train.copy()

In [57]:
X_train_new.drop(columns=['text','title'],inplace=True)

In [32]:
X_train_new['text'] bow.transform(corups_raw_test[0]).toarray()

In [53]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
model_bow = MultinomialNB(alpha=1.0)

In [54]:
model_bow.fit(sent_em_train,y_train)

ValueError: Found input variables with inconsistent numbers of samples: [71836, 35918]

In [ ]:
y_bow_pred = model_bow.predict(sent_em_test)
print(accuracy_score(y_test,y_bow_pred))

## Tf-IDF

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf = TfidfVectorizer(ngram_range=(1,1),max_features=2500)

In [34]:
sent_emtf_train = tf_idf.fit_transform(corups_raw).toarray()

In [35]:
sent_emtf_train[0]

In [52]:
snt_emtf_test = tf_idf.transform(corups_raw_test).toarray()

In [55]:
model_tf = MultinomialNB(alpha=1.0)
model_tf.fit(sent_emtf_train,y_train)
y_tf_pred = model_tf.predict(snt_emtf_test)
print(accuracy_score(y_test,y_tf_pred))

ValueError: Found input variables with inconsistent numbers of samples: [71836, 35918]

## Pretrained google-news-300

In [37]:
import gensim

In [38]:
import gensim.downloader as api
w2v_pre = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


ommon Word2Vec functions include most_similar, similarity, doesnt_match, get_vector, and vocabulary checks using key_to_index.

In [39]:
w2v_pre.most_similar('flower')

[('floral', 0.7493643164634705),
 ('flowers', 0.7488503456115723),
 ('roses', 0.697738766670227),
 ('orchid', 0.6928980350494385),
 ('tulip', 0.6629416346549988),
 ('peony', 0.6613222360610962),
 ('blooms', 0.6554170846939087),
 ('blossoms', 0.6527379155158997),
 ('chrysanthemum', 0.6500308513641357),
 ('anthurium', 0.6497662663459778)]

In [40]:
w2v_pre.similarity('man','woman')

np.float32(0.76640123)

In [41]:
w2v_pre.doesnt_match(['love','pain','peace','hate'])

'pain'

In [42]:
'cure' in w2v_pre.key_to_index

True

checks cure exist in dictionary or not

In [43]:
w2v_pre.most_similar(positive=['king','woman'],negative=['man'])

[('queen', 0.7118193507194519),
 ('monarch', 0.6189674139022827),
 ('princess', 0.5902431011199951),
 ('crown_prince', 0.5499460697174072),
 ('prince', 0.5377321839332581),
 ('kings', 0.5236844420433044),
 ('Queen_Consort', 0.5235945582389832),
 ('queens', 0.518113374710083),
 ('sultan', 0.5098593235015869),
 ('monarchy', 0.5087411403656006)]

it means      +king+woman-man

In [44]:
w2v_pre['king']

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

##Word2vec

In [45]:
from gensim.models import Word2Vec

w2v = Word2Vec(
    sentences=corups_tock,
    vector_size=300,
    window=5,
    min_count=2,
    sg=0,          # CBOW
    workers=4,
    epochs=10
)

sg=0 default - cbow , 1 for skip grams  
works = no. of cpu threads

all previous function can be used in this also just word need to exist in vocabulary

In [46]:
w2v.wv.index_to_key

['trump',
 'said',
 'state',
 'president',
 'would',
 'people',
 'year',
 'republican',
 'one',
 'new',
 'clinton',
 'obama',
 'also',
 'government',
 'house',
 'say',
 'reuters',
 'time',
 'donald',
 'american',
 'election',
 'country',
 'right',
 'white',
 'could',
 'party',
 'like',
 'united',
 'campaign',
 'told',
 'two',
 'official',
 'news',
 'last',
 'first',
 'group',
 'law',
 'hillary',
 'washington',
 'day',
 'video',
 'make',
 'former',
 'u',
 'even',
 'get',
 'court',
 'week',
 'vote',
 'medium',
 'security',
 'many',
 'want',
 'national',
 'democrat',
 'may',
 'woman',
 'leader',
 'bill',
 'police',
 'made',
 'russia',
 'political',
 'million',
 'image',
 'back',
 'twitter',
 'know',
 'take',
 'since',
 'way',
 'administration',
 'tax',
 'america',
 'support',
 'think',
 'month',
 'going',
 'percent',
 'according',
 'presidential',
 'senate',
 'member',
 'statement',
 'north',
 'attack',
 'democratic',
 'policy',
 'called',
 'via',
 'report',
 'office',
 'go',
 'well',
 'r

In [47]:
w2v.corpus_count

71836

In [48]:
w2v.wv.similar_by_word('dangerous')

[('frightening', 0.5186598300933838),
 ('reckless', 0.5072950124740601),
 ('impulsive', 0.47438547015190125),
 ('terrifying', 0.4514513611793518),
 ('unpredictable', 0.4514455199241638),
 ('irresponsible', 0.44319725036621094),
 ('irrational', 0.4417136013507843),
 ('destructive', 0.43497294187545776),
 ('heartless', 0.4308537542819977),
 ('provocative', 0.42848262190818787)]

In [49]:
w2v.wv['dangerous']

array([-1.0451123 ,  0.03824018, -1.3142681 , -0.38912815, -0.00287773,
        0.36548477,  0.27262008,  0.02745415, -0.8426489 , -1.7382668 ,
       -0.13418773, -0.24840443,  2.0731368 ,  0.18080075, -1.0389161 ,
       -1.0482144 ,  0.68429387,  0.49922857, -0.29353574, -0.43147224,
        1.2497277 ,  0.12035499, -1.1256064 , -0.7998919 , -0.5928196 ,
        1.6443888 ,  0.74042845, -1.0770905 , -1.7892616 ,  0.04014437,
        0.43450728,  0.27893466,  0.7914921 , -0.30210078,  0.2805541 ,
        1.0499276 ,  0.8197504 , -1.2882013 , -0.40536484,  0.10255886,
       -0.35896122,  1.3078935 , -1.1829197 , -0.4372219 ,  1.1465614 ,
       -0.5151099 ,  0.1934334 , -0.5750937 ,  0.20091277, -1.1674683 ,
        0.13466428, -0.521187  , -1.4847314 ,  1.2732983 , -0.40102214,
        0.8427273 , -0.16896623, -0.22079335, -0.14194094, -0.38072002,
        0.6725031 ,  1.5043033 ,  1.0069952 , -1.0754184 , -0.26684642,
       -0.7103254 , -0.8304368 , -2.0907454 ,  0.11596394, -2.20

In [50]:
w2v.wv['dangerous'].shape

(300,)

##AvgWord2Vec

In [51]:
def avg_word2vec(sent,model):
    words = simple_preprocess(sent)
    vectors = [model.wv[lem.lemmatize(word)] for word in words if word in w2v.wv.key_to_index]

    if len(vectors) == 0:
        return np.zeros(w2v.vector_size)

    return np.mean(vectors, axis=0)